README.md

Notification Test

---

README.md

Link with Slack Test

---

NetflixClone/NetflixClone/Controller/More/MoreViewController.swift

Fix: MoreViewController.swift

---

NetflixClone/NetflixClone/Extension/UIColorExtension.swift

흰색, 검은색, 로고 빨간색, 상황별로 회색을 4가지로 세분화

add: UIColor Extension

---

NetflixClone/NetflixClone.xcodeproj/project.pbxproj
NetflixClone/NetflixClone/Controller/More/MoreViewController.swift
NetflixClone/NetflixClone/Controller/Video/VideoControllerViewController.swift
NetflixClone/NetflixClone/Extension/DateExtension.swift
NetflixClone/NetflixClone/Model/Video/VideoModel.swift

Doro develop

---

NetflixClone/NetflixClone/Controller/More/MoreViewController.swift
NetflixClone/NetflixClone/Controller/Video/VideoControllerViewController.swift
NetflixClone/NetflixClone/Model/Video/VideoModel.swift

Fix: VideoController.swift #31

---

NetflixClone/NetflixClone/Controller/Global/TabBarController.swift
NetflixClone/NetflixClone/Controller/Search/SearchViewController.swift
NetflixClone/NetflixClone/View/Search/SearchView.swift

SearchViewController, NavigationController로 변경

fix: SearchViewController change to NavigationController

---

NetflixClone/NetflixClone/API/API.swift

requestOfPatch() 함수 추가
requestOfDelete() 함수 추가

Fix: API.swift

---

NetflixClone/NetflixClone.xcodeproj/project.pbxproj
NetflixClone/NetflixClone/API/API.swift
NetflixClone/NetflixClone/API/APIURL.swift
NetflixClone/NetflixClone/Controller/Login/LaunchScreen/LaunchScreenViewController.swift
NetflixClone/NetflixClone/Controller/Login/LoginViewController.swift
NetflixClone/NetflixClone/Controller/Login/SignUpViewController.swift
NetflixClone/NetflixClone/Controller/Profile/ProfileImageViewController.swift
NetflixClone/NetflixClone/View/Login/LaunchScreen/LaunchScreanView.swift

Fix: API request 함수 수정과 수정으로 인한 함수 요청 부분 수정
Complete: LaunchScreen 작업 완료
#20

Doro develop 

---

NetflixClone/NetflixClone/Extension/CGFloatExtension.swift

Fix: CGFloatExtension.swift

---

NetflixClone/NetflixClone/Controller/Login/LoginViewController.swift
NetflixClone/NetflixClone/View/Login/LoginView.swift
NetflixClone/NetflixClone/View/Login/SignUpView.swift

Complete: LoginView

---

NetflixClone/NetflixClone/Controller/Login/LoginViewController.swift
NetflixClone/NetflixClone/Controller/Login/SignUpViewController.swift
NetflixClone/NetflixClone/View/Login/LoginView.swift
NetflixClone/NetflixClone/View/Login/SignUpView.swift

Fix: Login, SignUp

---

NetflixClone/NetflixClone/View/Video/VideoView.swift

Fix: VideoView.swift

---

NetflixClone/NetflixClone.xcodeproj/project.pbxproj
NetflixClone/NetflixClone/Controller/Home/HomeViewController.swift
NetflixClone/NetflixClone/Controller/Preview/PreViewController.swift

PreViewController 추가, HomeController selectCell() 메소드 present 수정

Fix: Add PreviewController, HomeController modifyied

---

NetflixClone/NetflixClone/Controller/Profile/AddProfileViewController.swift
NetflixClone/NetflixClone/Controller/Profile/ChangeProfileViewController.swift
NetflixClone/NetflixClone/Controller/Profile/ProfileImageViewController.swift
NetflixClone/NetflixClone/Controller/Profile/ProfileViewController.swift

1. ProfileViewController url 수정
2. AddProfileViewController delete, update url 수정
3. ProfileImageViewController url 수정
4. 회원가입시 처음 들어오는 이미지 고정. 그 이후로는 랜덤 이미지로

Youkyung's project merge

---

NetflixClone/NetflixClone/Controller/Content/ContentViewController.swift
NetflixClone/NetflixClone/Controller/Global/TabBarController.swift
NetflixClone/NetflixClone/Controller/SavedContentsList/SavedContentsListViewController.swift
NetflixClone/NetflixClone/Model/SavedContentsList/DownLoadManager.swift
NetflixClone/NetflixClone/Model/SavedContentsList/HaveSaveContentsProfile.swift
NetflixClone/NetflixClone/Model/SavedContentsList/SaveContent.swift
NetflixClone/NetflixClone/Model/SavedContentsList/SaveFileManager.swift
NetflixClone/NetflixClone/Model/SavedContentsList/SavedContentsListModel.swift
NetflixClone/NetflixClone/View/Cell/SavedContentCell/SavedContentCell.swift
NetflixClone/NetflixClone/View/Cell/SavedContentCell/SavedContentHeaderView.swift
NetflixClone/NetflixClone/View/SavedContentsList/SaveContentStatusView.swift

Fix: SavedContentHeaderView

---

NetflixClone/NetflixClone/Controller/Content/ContentViewController.swift
NetflixClone/NetflixClone/Controller/SavedContentsList/SavedContentsListViewController.swift
NetflixClone/NetflixClone/Model/SavedContentsList/DownLoadManager.swift
NetflixClone/NetflixClone/View/Cell/SavedContentCell/SavedContentCell.swift
NetflixClone/NetflixClone/View/SavedContentsList/SaveContentStatusView.swift

Cell 에서 Notification이 잘못 등록되는 버그 수정

Fix: SavedContentCell

---

NetflixClone/NetflixClone/Controller/Content/ContentViewController.swift
NetflixClone/NetflixClone/Controller/Global/CanSaveViewController.swift
NetflixClone/NetflixClone/Controller/SavedContentsList/SavedContentsListViewController.swift
NetflixClone/NetflixClone/Model/SavedContentsList/DownLoadManager.swift
NetflixClone/NetflixClone/Model/SavedContentsList/DownLoading.swift
NetflixClone/NetflixClone/Model/SavedContentsList/HaveSaveContentsProfile.swift
NetflixClone/NetflixClone/Model/SavedContentsList/SaveContent.swift
NetflixClone/NetflixClone/Model/SavedContentsList/SaveFileManager.swift
NetflixClone/NetflixClone/Model/SavedContentsList/SavedContentsListModel.swift
NetflixClone/NetflixClone/View/Cell/SavedContentCell/SavedContentCell.swift
NetflixClone/NetflixClone/View/SavedContentsList/SaveContentStatusView.swift

Complete: DownLoad Task

---

NetflixClone/NetflixClone/Controller/Content/ContentViewController.swift
NetflixClone/NetflixClone/Controller/Global/BaseViewController.swift
NetflixClone/NetflixClone/Controller/Video/VideoController.swift
NetflixClone/NetflixClone/Extension/UIViewControllerExtension.swift
NetflixClone/NetflixClone/Model/Video/VideoModel.swift
NetflixClone/NetflixClone/View/Cell/Content/PosterTableViewCell.swift
NetflixClone/NetflixClone/View/Video/VideoView.swift

present의 매개변수를 콘텐츠의 아이디값으로 받게 수정
슬라이더의 불확실한 작동 수정
#123

Fix: VideoController

---

NetflixClone/NetflixClone/Controller/Video/VideoController.swift
NetflixClone/NetflixClone/Model/Content/ContentModel.swift
NetflixClone/NetflixClone/Model/Video/VideoModel.swift

Fix: VideoController.swift

---

NetflixClone/NetflixClone/Controller/Home/HomeViewController.swift
NetflixClone/NetflixClone/View/Cell/ContentsBasicItem.swift
NetflixClone/NetflixClone/View/Cell/Home/CollectionCell/Top10CollectionViewCell.swift
NetflixClone/NetflixClone/View/Cell/Home/CollectionCell/WatchContentsCollectionViewCell.swift
NetflixClone/NetflixClone/View/Cell/Home/LatestMovieTableViewCell.swift
NetflixClone/NetflixClone/View/Cell/Home/WatchContentsTableViewCell.swift

fix: HomeController Kingfisher

---

NetflixClone/NetflixClone/Controller/SavedContentsList/SavedContentsListViewController.swift
NetflixClone/NetflixClone/Model/SavedContentsList/SavedContentsListModel.swift

저장한 컨텐츠 중 시청중인 컨텐츠 배열 반환 함수 작성 완료

Fix: SavedContentsListModel.swift

---

NetflixClone/NetflixClone.xcodeproj/project.pbxproj
NetflixClone/NetflixClone/Controller/SavedContentsList/FindCanSaveViewController.swift
NetflixClone/NetflixClone/View/SavedContentsList/FindCanSaveContentView.swift

Add: FindCanSaveContentViewController.swift
Add: FindCanSaveContentView.swift

Add: SavedContentList

---

NetflixClone/NetflixClone/View/Cell/SavedContentCell/FindStorableCollectionViewCell.swift

Fix: FindStorableCollectionViewCell.swift

---

NetflixClone/NetflixClone/Controller/Search/SearchViewController.swift

Fix: Modified present ContentViewController

Fix: add comment

---

NetflixClone/NetflixClone/Controller/Home/HomeViewController.swift
NetflixClone/NetflixClone/View/Cell/Home/LatestMovieTableViewCell.swift

fix: HomeView recommendCell

---

NetflixClone/NetflixClone/Assets.xcassets/프로필아이콘/저장펜슬.imageset/Contents.json
NetflixClone/NetflixClone/Assets.xcassets/프로필아이콘/플러스.imageset/Contents.json
NetflixClone/NetflixClone/Controller/Preview/PreViewController.swift
NetflixClone/NetflixClone/View/Preview/PreviewView.swift

PreViewController present 딜레이 수정

Preview feature

---

NetflixClone/NetflixClone/Controller/Video/VideoController.swift
NetflixClone/NetflixClone/View/Video/VideoView.swift

Fix: rewind, slip Button Animation
Fix: playerLayer frame

Fix: VideoConrtoller.swift

---

NetflixClone/NetflixClone/Controller/Search/SearchViewController.swift
README.md

Fix: add sample Clips to readme.md

Add: add sample Clips to readme.md
